// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:274a6a84b5b532a690bdba03e4567a52cb673710fab94faeade518edf869eae1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import gleeunit
import gleeunit/should
import kreuzberg

// extract_bytes empty MIME async
pub fn async_extract_bytes_empty_mime_test() {
  kreuzberg.extract_bytes("text/plain.txt", "", "{}") |> should.be_error()
}

// extract_bytes unsupported MIME async
pub fn async_extract_bytes_invalid_mime_test() {
  kreuzberg.extract_bytes("text/plain.txt", "application/x-nonexistent", "{}") |> should.be_error()
}
