// Generated by alef. Do not edit by hand.
// No fixture-driven tests for Gleam — e2e tests require HTTP fixtures
// or non-HTTP fixtures with gleam-specific call overrides.
import gleeunit
import gleeunit/should

pub fn main() {
  gleeunit.main()
}

pub fn compilation_smoke_test() {
  True |> should.equal(True)
}
