// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:70f4e0f25f02e801c99299406a6f4e4408766f43b14614d80e160e8bd3f3e38d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import gleeunit
import gleeunit/should
import kreuzberg

import gleam/string

// Get file extensions for DOCX MIME type
pub fn extensions_docx_test() {
  let result = kreuzberg.get_extensions_for_mime("application/vnd.openxmlformats-officedocument.wordprocessingml.document")
  result |> should.be_ok()
}

// Get file extensions for HTML MIME type
pub fn extensions_html_test() {
  let result = kreuzberg.get_extensions_for_mime("text/html")
  result |> should.be_ok()
}

// Get file extensions for PDF MIME type
pub fn extensions_pdf_test() {
  let result = kreuzberg.get_extensions_for_mime("application/pdf")
  result |> should.be_ok()
  result |> string.contains("pdf") |> should.equal(True)
}
